export enum NodeType {
  trigger = 1,
  action = 2,
  message = 3,
  sendPrivateMessage = 4,
  note = 5,
  condition = 6,
  requestService = 7,
  sendNotification = 8,
  code = 9,
}

export const NODE_TYPE_TRIGGER_GENERAL_MESSAGE_INCOMING = 'trigger.general.incoming.message' as const
export const NODE_TYPE_GENERAL_MESSAGE_SIMPLE = 'node.messaging.general.send.simple' as const
export const NODE_TYPE_GENERAL_MESSAGE_LIST = 'node.messaging.general.send.list' as const
export const NODE_TYPE_GENERAL_MESSAGE_FILE = 'node.messaging.general.send.file' as const
export const NODE_TYPE_GENERAL_MESSAGE_VOICE = 'node.messaging.general.send.voice' as const
export const NODE_TYPE_GENERAL_MESSAGE_IMAGE = 'node.messaging.general.send.image' as const
export const NODE_TYPE_CONDITION = 'node.condition' as const
export const NODE_TYPE_REQUEST_SERVICE = 'node.request.service' as const
export const NODE_TYPE_SEND_NOTIFICATION = 'node.app.send.notificaion' as const
export const NODE_TYPE_PRIVATE_MESSAGE = 'node.chat.send.private.message' as const
export const NODE_TYPE_NOTE = 'node.note' as const
export const NODE_TYPE_CODE = 'node.code' as const
export const NODE_TYPE_ADDTAG = 'node.room.add.tag' as const
export const NODE_TYPE_REMOVETAG = 'node.room.remove.tag' as const
export const NODE_TYPE_SETVAR = 'node.room.set.var' as const
export const NODE_TYPE_START_AUTOMATION = 'node.flow.start.automation' as const
export const NODE_TYPE_STOP_CURRENTAUTOMATION = 'node.flow.stop.me' as const

export type NodeTypesType = 
  typeof NODE_TYPE_TRIGGER_GENERAL_MESSAGE_INCOMING |
  typeof NODE_TYPE_GENERAL_MESSAGE_SIMPLE |
  typeof NODE_TYPE_GENERAL_MESSAGE_LIST |
  typeof NODE_TYPE_GENERAL_MESSAGE_FILE |
  typeof NODE_TYPE_GENERAL_MESSAGE_VOICE |
  typeof NODE_TYPE_GENERAL_MESSAGE_IMAGE |
  typeof NODE_TYPE_CONDITION |
  typeof NODE_TYPE_REQUEST_SERVICE |
  typeof NODE_TYPE_SEND_NOTIFICATION |
  typeof NODE_TYPE_PRIVATE_MESSAGE |
  typeof NODE_TYPE_NOTE |
  typeof NODE_TYPE_CODE |
  typeof NODE_TYPE_ADDTAG |
  typeof NODE_TYPE_REMOVETAG |
  typeof NODE_TYPE_SETVAR |
  typeof NODE_TYPE_START_AUTOMATION |
  typeof NODE_TYPE_STOP_CURRENTAUTOMATION
  

export const nodeTypes = {
  NODE_TYPE_TRIGGER_GENERAL_MESSAGE_INCOMING : NODE_TYPE_TRIGGER_GENERAL_MESSAGE_INCOMING,
  NODE_TYPE_GENERAL_MESSAGE_SIMPLE : NODE_TYPE_GENERAL_MESSAGE_SIMPLE,
  NODE_TYPE_GENERAL_MESSAGE_LIST : NODE_TYPE_GENERAL_MESSAGE_LIST,
  NODE_TYPE_GENERAL_MESSAGE_FILE : NODE_TYPE_GENERAL_MESSAGE_FILE,
  NODE_TYPE_GENERAL_MESSAGE_VOICE : NODE_TYPE_GENERAL_MESSAGE_VOICE,
  NODE_TYPE_GENERAL_MESSAGE_IMAGE : NODE_TYPE_GENERAL_MESSAGE_IMAGE,
  NODE_TYPE_CONDITION : NODE_TYPE_CONDITION,
  NODE_TYPE_REQUEST_SERVICE : NODE_TYPE_REQUEST_SERVICE,
  NODE_TYPE_SEND_NOTIFICATION : NODE_TYPE_SEND_NOTIFICATION,
  NODE_TYPE_PRIVATE_MESSAGE : NODE_TYPE_PRIVATE_MESSAGE,
  NODE_TYPE_NOTE : NODE_TYPE_NOTE,
  NODE_TYPE_CODE : NODE_TYPE_CODE,
  NODE_TYPE_ADDTAG : NODE_TYPE_ADDTAG,
  NODE_TYPE_REMOVETAG : NODE_TYPE_REMOVETAG,
  NODE_TYPE_SETVAR : NODE_TYPE_SETVAR,
  NODE_TYPE_START_AUTOMATION : NODE_TYPE_START_AUTOMATION,
  NODE_TYPE_STOP_CURRENTAUTOMATION : NODE_TYPE_STOP_CURRENTAUTOMATION,
} as const

export const nodeTypeList = [
  NODE_TYPE_TRIGGER_GENERAL_MESSAGE_INCOMING,
  NODE_TYPE_GENERAL_MESSAGE_SIMPLE,
  NODE_TYPE_GENERAL_MESSAGE_LIST,
  NODE_TYPE_GENERAL_MESSAGE_FILE,
  NODE_TYPE_GENERAL_MESSAGE_VOICE,
  NODE_TYPE_GENERAL_MESSAGE_IMAGE,
  NODE_TYPE_CONDITION,
  NODE_TYPE_REQUEST_SERVICE,
  NODE_TYPE_SEND_NOTIFICATION,
  NODE_TYPE_PRIVATE_MESSAGE,
  NODE_TYPE_NOTE,
  NODE_TYPE_CODE,
  NODE_TYPE_ADDTAG,
  NODE_TYPE_REMOVETAG,
  NODE_TYPE_SETVAR,
  NODE_TYPE_START_AUTOMATION,
  NODE_TYPE_STOP_CURRENTAUTOMATION,
]